<h4>Introduction Tensors</h4>

In [1]:
import tensorflow as tf
import tensorflow_probability as tfp
import numpy as np

print(tf.__version__)

scalar = tf.constant(7, dtype=tf.int32)
print(scalar)
print(scalar.ndim)
print(scalar.shape)
print(scalar.dtype)
print(type(scalar))
print(tf.size(scalar).numpy(), '\n') # Total of elements in our Tensor

vector = tf.constant([10, 10], dtype=tf.int64)
print('VECTOR:', vector)
print(vector.ndim)
print(vector.shape)
print(vector.dtype)
print(type(vector))
print(tf.size(vector).numpy(), '\n') # Total of elements in our Tensor

matrix = tf.constant([[10.0, 10.0], [20, 20], [30, 30]], dtype=tf.float64)
print('MATRIX:', matrix)
print(matrix.ndim)
print(matrix.shape)
print(matrix.dtype)
print(type(matrix))
print(tf.size(matrix).numpy(), '\n') # Total of elements in our Tensor

tensor = tf.constant([[[10.0, 10.0], [20, 20], [30, 30]], [[40.0, 40.0], [50, 50], [60, 60]], [[70.0, 40.0], [80.0, 50], [90.0, 60]]], dtype=tf.float16)
print('TENSOR:',tensor)
print(tensor.ndim)
print(tensor.shape)
print(tensor.dtype)
print(type(tensor))
print(tf.size(tensor).numpy(), '\n') # Total of elements in our Tensor

numpy_array = np.array([1, 10, 100, 1000], dtype=np.int16)
print(numpy_array.dtype)
print(numpy_array)
print(numpy_array.ndim)
print(tf.size(numpy_array))
tensor_array = tf.constant(numpy_array)
print(tensor_array)
print(tensor_array.ndim)
print(tf.size(tensor_array))
cast = tf.cast(tensor_array, dtype=tf.float32)
print(cast)

r = tf.random.uniform(shape=[50, 50, 50], dtype=tf.float16)
print(r)
print(r.ndim)

2022-04-20 10:09:04.270784: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-04-20 10:09:04.270848: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


2.8.0
tf.Tensor(7, shape=(), dtype=int32)
0
()
<dtype: 'int32'>
<class 'tensorflow.python.framework.ops.EagerTensor'>
1 

VECTOR: tf.Tensor([10 10], shape=(2,), dtype=int64)
1
(2,)
<dtype: 'int64'>
<class 'tensorflow.python.framework.ops.EagerTensor'>
2 

MATRIX: tf.Tensor(
[[10. 10.]
 [20. 20.]
 [30. 30.]], shape=(3, 2), dtype=float64)
2
(3, 2)
<dtype: 'float64'>
<class 'tensorflow.python.framework.ops.EagerTensor'>
6 

TENSOR: tf.Tensor(
[[[10. 10.]
  [20. 20.]
  [30. 30.]]

 [[40. 40.]
  [50. 50.]
  [60. 60.]]

 [[70. 40.]
  [80. 50.]
  [90. 60.]]], shape=(3, 3, 2), dtype=float16)
3
(3, 3, 2)
<dtype: 'float16'>
<class 'tensorflow.python.framework.ops.EagerTensor'>
18 

int16
[   1   10  100 1000]
1
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor([   1   10  100 1000], shape=(4,), dtype=int16)
1
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor([   1.   10.  100. 1000.], shape=(4,), dtype=float32)
tf.Tensor(
[[[0.1445  0.4229  0.2559  ... 0.2842  0.834   0.55   ]
  [0.166   0.6523  0.1309 

2022-04-20 10:09:07.243983: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-04-20 10:09:07.244022: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-04-20 10:09:07.244044: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (felipe-Inspiron-3501): /proc/driver/nvidia/version does not exist
2022-04-20 10:09:07.245189: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


<h4>Variable</h4>

In [2]:
var = tf.Variable([10, 8, 10], dtype=tf.int16)
print(var)
print(type(var), '\n')
var[0].assign(500)
print(var)
print(var.dtype)
print(tf.size(var).numpy()) # Total of elements in our Tensor

<tf.Variable 'Variable:0' shape=(3,) dtype=int16, numpy=array([10,  8, 10], dtype=int16)>
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'> 

<tf.Variable 'Variable:0' shape=(3,) dtype=int16, numpy=array([500,   8,  10], dtype=int16)>
<dtype: 'int16'>
3


<h4>Random Tensor</h4>

In [3]:
random = tf.random.Generator.from_seed(42).normal(shape=(3, 2), dtype=tf.float16)
print(random)
print(random.ndim)
print(random.shape)
print(random.dtype)
print(tf.size(random).numpy()) # Total of elements in our Tensor

tf.Tensor(
[[-0.7563  -0.06854]
 [ 0.0759  -1.258  ]
 [-0.2319  -1.811  ]], shape=(3, 2), dtype=float16)
2
(3, 2)
<dtype: 'float16'>
6


<h4>Shuffling the order of tensors</h4>

In [4]:
shuffled = tf.random.Generator.from_seed(42).normal(shape=(30, 50))
print(shuffled.ndim)
print(shuffled.shape)
print(shuffled.dtype)
print(tf.size(shuffled))
print(shuffled)
print(tf.random.shuffle(shuffled, seed=32))
print(tf.size(shuffled).numpy()) # Total of elements in our Tensor

not_shuffled = tf.constant([[2, 3.25], 
                            [8, 3.23], 
                            [20, 3.22],
                            [22, 3.27]])
print(not_shuffled)
print(tf.random.shuffle(not_shuffled))

tf.random.set_seed(33) # Global level random seed
print(tf.random.shuffle(not_shuffled))

2
(30, 50)
<dtype: 'float32'>
tf.Tensor(1500, shape=(), dtype=int32)
tf.Tensor(
[[-0.7565803  -0.06854702  0.07595026 ...  0.6617961   0.01380118
  -0.24827152]
 [ 1.2111493  -0.7199124  -0.04082382 ... -0.3741098  -0.28709963
   1.5089895 ]
 [-0.14833727 -1.2846565   0.5484313  ... -0.29996362 -0.7382552
   1.2053189 ]
 ...
 [ 1.0943383   0.255803    0.8011465  ...  2.0650482  -0.75586045
  -1.5107038 ]
 [-0.50980395  1.1796211   0.4873755  ...  0.29254746  0.509817
   1.1662555 ]
 [ 0.7567598  -0.01560464 -0.9169527  ...  0.1947453   0.5656089
   0.18439196]], shape=(30, 50), dtype=float32)
tf.Tensor(
[[-0.45561165  1.69945     0.32171428 ...  0.3040326   1.3539944
  -0.35777435]
 [ 0.2519273  -0.6945314   0.02182634 ...  0.7617905  -0.41406497
  -2.2834349 ]
 [-0.6038851  -0.08852839 -1.2040683  ... -1.0428714  -0.73970354
   0.0177109 ]
 ...
 [-0.88051033 -0.32426047 -2.4847078  ...  0.34223038 -0.3702979
  -0.99169385]
 [ 0.455365    0.18552932 -2.0545108  ...  0.17139332 -0.21565

<h4>Indexing</h4>

In [5]:
matrix = tf.random.Generator.from_seed(42).normal(shape=(3, 5))
print(matrix)
print(tf.expand_dims(matrix, axis=-1))
print(tf.expand_dims(matrix, axis=0))

tf.Tensor(
[[-0.7565803  -0.06854702  0.07595026 -1.2573844  -0.23193763]
 [-1.8107855   0.09988727 -0.50998646 -0.7535805  -0.57166284]
 [ 0.1480774  -0.23362993 -0.3522796   0.40621263 -1.0523509 ]], shape=(3, 5), dtype=float32)
tf.Tensor(
[[[-0.7565803 ]
  [-0.06854702]
  [ 0.07595026]
  [-1.2573844 ]
  [-0.23193763]]

 [[-1.8107855 ]
  [ 0.09988727]
  [-0.50998646]
  [-0.7535805 ]
  [-0.57166284]]

 [[ 0.1480774 ]
  [-0.23362993]
  [-0.3522796 ]
  [ 0.40621263]
  [-1.0523509 ]]], shape=(3, 5, 1), dtype=float32)
tf.Tensor(
[[[-0.7565803  -0.06854702  0.07595026 -1.2573844  -0.23193763]
  [-1.8107855   0.09988727 -0.50998646 -0.7535805  -0.57166284]
  [ 0.1480774  -0.23362993 -0.3522796   0.40621263 -1.0523509 ]]], shape=(1, 3, 5), dtype=float32)


<h4>Absolute Values</h4>

In [6]:
a = tf.constant([-7, -10, - 19, 5, 2])
tf.abs(a)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 7, 10, 19,  5,  2], dtype=int32)>

<h4>Min, Max, Mean</h4>

In [11]:
a = tf.constant(np.random.randint(0, 100, size=50), dtype=tf.float16)
b = tf.random.uniform(shape=[50], dtype=tf.float16)
print(a)
print(b)
print(tf.reduce_min(a))
print(tf.reduce_max(a))
print(tf.reduce_mean(a))
print(tf.reduce_sum(a))
print(f'Square Root: {tf.math.sqrt(a)} \n')
print(f'Positional Max: {tf.argmax(a)} - Value: {a[tf.argmax(a)]} \n')
print(tf.math.reduce_std(a))
print(tfp.stats.variance(a))    
print(tfp.stats.percentile(a, q=50))

tf.Tensor(
[82. 31. 87. 41. 93. 47. 72. 73. 78. 72. 61. 24. 93. 65. 42. 25. 92. 55.
 39. 95. 73. 85. 60. 64. 93. 32. 97. 85. 61. 38. 58. 62. 68. 51. 33. 59.
 95. 74. 14. 27. 78. 58. 99. 92. 61.  3. 11. 30.  5.  5.], shape=(50,), dtype=float16)
tf.Tensor(
[0.1035  0.4912  0.07324 0.3428  0.7656  0.9004  0.207   0.8564  0.4678
 0.5986  0.0371  0.7773  0.838   0.4463  0.4717  0.717   0.5293  0.8896
 0.84    0.9873  0.997   0.5166  0.6396  0.1592  0.1621  0.1416  0.3018
 0.7637  0.659   0.125   0.758   0.1973  0.791   0.6426  0.4766  0.4639
 0.496   0.254   0.6797  0.6064  0.674   0.9766  0.6436  0.6436  0.871
 0.6357  0.8584  0.1797  0.0166  0.5303 ], shape=(50,), dtype=float16)
tf.Tensor(3.0, shape=(), dtype=float16)
tf.Tensor(99.0, shape=(), dtype=float16)
tf.Tensor(58.75, shape=(), dtype=float16)
tf.Tensor(2938.0, shape=(), dtype=float16)
Square Root: [9.055 5.566 9.33  6.402 9.64  6.855 8.484 8.55  8.83  8.484 7.81  4.9
 9.64  8.06  6.48  5.    9.59  7.418 6.246 9.75  8.55  9.22  7.74